Controllers and Repository for Events and Labels
bprof-spec-codes/workcal pull request #26
Opened 2023-09-25 09:16 UTC by bbence01

Controllers and Repository for Events and Labels

2023-10-07 10:22 UTC, gergo2222 requested changes

2023-10-07 10:22 UTC, gergo2222 commented on workcal/aspnet-core/workcal/Services/EventAppService.cs
> +               // Id = GuidGenerator.Create(),
please delete comment before merge!

2023-10-07 10:22 UTC, gergo2222 commented on workcal/aspnet-core/workcal/Services/EventAppService.cs
> +        public async Task CreateAsync(CreateEventDto input)
event instead of input

2023-10-07 10:22 UTC, gergo2222 commented on workcal/aspnet-core/workcal/Services/EventAppService.cs
> +            var eventEntity = await _eventRepository.GetAsync(id);  // Retrieve the existing event
Please make an exception if the given id is not exist then throw exception or return a badrequest!

2023-10-07 10:22 UTC, gergo2222 commented on workcal/aspnet-core/workcal/Services/EventAppService.cs
> +            await _eventRepository.InsertAsync(eventEntity);
try catch if something failing then not break the backend!

2023-10-07 10:22 UTC, gergo2222 commented on workcal/aspnet-core/workcal/Services/EventAppService.cs
> +            var eventEntity = await _eventRepository.GetAsync(id);
if no entity match with given id then throw an exception and return badrequest!

2023-10-07 10:22 UTC, gergo2222 commented on workcal/aspnet-core/workcal/Services/EventAppService.cs
> +            await _eventRepository.DeleteAsync(id);
try catch badrequest when no entity match given id

2023-10-07 10:22 UTC, gergo2222 commented on workcal/aspnet-core/workcal/Services/LabelAppService.cs
> +               // Id = GuidGenerator.Create(),
remove comment before merge!

2023-10-07 10:22 UTC, gergo2222 commented on workcal/aspnet-core/workcal/Services/LabelAppService.cs
> +    public class LabelAppService : ApplicationService, ILabelAppService
Same all comment as EventService

2023-10-18 06:48 UTC, Besz5 approved these changes

2023-10-20 14:59 UTC, JuhaszMarton approved these changes

2023-10-23 15:53 UTC, gergo2222 commented
Is there any update in thiis pr ? or when will be?

2023-11-06 14:46 UTC, closed without merging